# =========================================================================
# LLM 推論專屬設定檔 (LLM Inference Config)
# =========================================================================

# ================= 1. 檔案路徑設定 (Paths) =================
paths:
  # --- 輸入路徑 (Inputs) ---
  dataPath: "data/bcvcdr_raw/BCVCDR_Processed.csv"
  promptCmbPath: "data/prompt_output/test_manual_prompts.csv" # 從 Prompt 模組讀取組合好的清單
  # --- 輸出路徑 (Outputs)(可自訂) ---
  rawPromptCmbOutputPath: "data/test_V9/Temp.csv" #佔存檔
  allPromptsCmbResultPath: "data/test_V9/raw.csv"         #生的
  singlePromptCmbOutputDir: "data/test_V9/singleOutput" #裡面放單獨prompt的結果
  promptCmbPartialInfoPath: "data/test_V9/result.csv"      #放處理過的
  promptCmbFullInfoPath: "data/test_V9/test_merge.csv"     #所有欄位總成(ID/titlr/abstract/entity/relation/processed/relation)
  promptCmbEvalDir: "data/test_V9/eval"       #放圖表的資料夾  

# ================= 2. LLM 模型與連線設定 =================
selectedModels: ["gemma3:270m", "llama3.2:1b", "phi3:latest"]

testLimits: 10

ollamaServer:
  url: "http://localhost:11434/api/chat"
  timeout: 600

llmOptions:
  temperature: 0      
  num_predict: -1     
  num_ctx: 8192
  num_gpu: 99
  repeat_penalty: 1.1   

# ================= 3. 執行與批量設定 =================

concurrencyPerModel: 8
maxConcurrentModels: 1

pairSettings:
  enabled: true
  pairNumbers: 10

# ================= 4. User Prompt 模板 =================
taskTemplate: |
  Title: {title}
  Abstract: {abstract}

  Task: Determine if the Chemical induces the Disease for the following pairs based strictly on the text.

  pairs to analyze:
  {pairsContent}

  IMPORTANT OUTPUT RULES:
  1. Output ONLY a numbered list.
  2. Format: "Pair X: Yes" or "Pair X: No".
  3. Do NOT provide explanations.
  4. Do NOT use Markdown formatting.