#ML部分 路徑自訂 boruta
#(main_prompt generatodo )
#3.EVAL清單 4.sampledata

# =========================================================================
# LLM 推論專屬設定檔 (LLM Inference Config)
# =========================================================================

# ================= 1. 檔案路徑設定 (Paths) =================
paths:
  # --- 輸入路徑 (Inputs) ---
  dataPath: "data/bcvcdr_raw/BCVCDR_Processed.csv"
  promptsPath: "data/prompt_output/test_manual_prompts.csv" # 從 Prompt 模組讀取組合好的清單
  # --- 輸出路徑 (Outputs)(可自訂) ---
  mainOutputDir: "data/test_V2/"
  singlePromptOutputDir: "data/test_V2/single/output" #裡面放單獨prompt的結果
  evalDataDir: "data/test_V2/plots"       #放圖表
  rawOutputPath: "data/test_V2/raw.csv"         #生的                
  resultOutputPath: "data/test_V2/result.csv"      #放處理過的
  mergedLlmOutputPath: "data/test_V2/test_merge.csv"     #所有欄位總成(ID/titlr/abstract/entity/relation/processed/relation) 


# ================= 2. LLM 模型與連線設定 =================
selectedModels:
  #- "gemma3:270m"
  - "llama3.2:1b"

testLimits: 20

ollamaServer:
  url: "http://localhost:11434/api/chat"
  timeout: 600

llmHyperparameters:
  temperature: 0      
  num_predict: -1     
  num_ctx: 8192
  num_gpu: 99
  repeat_penalty: 1.1   

# ================= 3. 執行與批量設定 =================
executionSettings:
  modelConcurrentRequests: 12

pairSettings:
  enabled: true
  pairNumbers: 10
  saveEveryNBatches: 100

# ================= 4. User Prompt 模板 =================
taskTemplate: |
  Title: {title}
  Abstract: {abstract}

  Task: Determine if the Chemical induces the Disease for the following items based strictly on the text.

  Items to analyze:
  {items_content}

  IMPORTANT OUTPUT RULES:
  1. Output ONLY a numbered list.
  2. Format: "Item X: Yes" or "Item X: No".
  3. Do NOT provide explanations.
  4. Do NOT use Markdown formatting.